### ISSUE TITLE
examle shemas of common file types

### ISSUE THREAD

**Issue by furesoft** [Epidal/BeeSchema#14]
please provide example schemas of common file types like zip, png, clamfs, squaschfs and so one. examples: https://github.com/kaitai-io/kaitai_struct_formats/tree/ff88bb37ea1965ccd9ede33b71ac4af9e7cd3986

**Comment by Michael-K-GH** [comment]
There is already an example that covers all the current functionality in the readme.  Creating further examples would be redundant.
